dist: focal
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f92652803cd9_key -iv $encrypted_f92652803cd9_iv -in multi-k8-463101-a8bc41f882f2.json.enc -out multi-k8-463101-a8bc41f882f2.json  -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8-463101-a8bc41f882f2.json
  - gcloud config set project multi-k8-463101 
  - gcloud config set compute/zone   us-central1-a
  - gcloud container clusters get-credentials my-first-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t viswa2489/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true viswa2489/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
